version: "3.9"
services:
  db:
    image: timescale/timescaledb:latest-pg15
    restart: always
    container_name: grana-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grana
  db-shadow:
    image: timescale/timescaledb:latest-pg15
    restart: always
    container_name: grana-db-shadow
    ports:
      - "5455:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grana-shadow
