name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      timescale:
        image: timescale/timescaledb:latest-pg15
        env:
          POSTGRES_DB: grana
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5433:5432
      timescale-shadow:
        image: timescale/timescaledb:latest-pg15
        env:
          POSTGRES_DB: grana-shadow
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5455:5432

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Setup environment variables
        run: |
          cp .env.example .env
          
      - name: Setup Database
        run: |
          tar -xf ./prisma/devices_small.tar.gz -C ./prisma
          npm run local:migrate
          npm run local:seed
          
      - name: Build application
        run: npm build

      - name: Run all tests
        run: npm run test:integration
